<?php 
	$id= $_GET['id'];
	$connect = mysql_connect("sql304.freevnn.com","freev_16066123","123456") or die("Server disconnect");
	mysql_select_db("freev_16066123_quanlybenhnhan",$connect);
	$sql="SELECT * FROM Thong_tin_ca_nhan WHERE id=' " .$id. " ' ";
	$query = mysql_query($sql);
	$data=mysql_fetch_assoc($query);
	$Ho_Va_Ten=$Gioi_tinh=$Nam_Sinh=$Que_Quan=$email=$SDT= "";
	if(isset($_POST['ok'])){
		if($_POST['Ho_Va_Ten']==null){
			$errorName="vui long nhap ho va ten";
		}else{
			$Ho_Va_Ten=$_POST['Ho_Va_Ten'];
		}
		if($_POST['Gioi_tinh']==null){
			$errorGender="vui long nhap Gioi_tinh";
		}else{
			$Gioi_tinh=$_POST['Gioi_tinh'];
		}
		if($_POST['Nam_Sinh']==null){
			$errorDate="vui long nhap Nam_Sinh";
		}else{
			$Nam_Sinh=$_POST['Nam_Sinh'];
		}
		if($_POST['Que_Quan']==null){
			$errorAddress="vui long nhap Dia Chi";
		}else{
			$Que_Quan=$_POST['Que_Quan'];
		}
		if($_POST['email']==null){
			$errorEmail="vui long nhap Email";
		}else{
			$email=$_POST['email'];
		}
		if($_POST['SDT']==null){
			$errorPhone="vui long nhap so dien thoai";
		}else{
			$SDT=$_POST['SDT'];
		}
		if($Ho_Va_Ten && $Gioi_tinh && $Nam_Sinh && $Que_Quan && $email && $SDT){
			$sqlEdit="UPDATE Thong_tin_ca_nhan 
                      SET Ho_Va_Ten='".$Ho_Va_Ten."',
                      Gioi_tinh='".$Gioi_tinh."',
                      Nam_Sinh='".$Nam_Sinh."',
                      Que_Quan='". $Que_Quan."',
                      email='".$email."',
                      SDT='".$SDT."' WHERE id='".$id."'
                    ";
            mysql_query($sqlEdit);
    		header("location:list.php");
		}
	}

?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="shortcut icon" href="http://phongkham2.freevnn.com/website/pictures/logo5.png"/>
<title>Cập Nhật</title>
<link rel="stylesheet" type="text/css" href="http://phongkham2.freevnn.com/website/style/view.css" media="all">
<script type="text/javascript" src="http://phongkham2.freevnn.com/website/style/view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="http://phongkham2.freevnn.com/website/style/top.png" alt="">
	<div id="form_container">
		<h1><a>Cập Nhật</a></h1>
		<form id="form_1030969" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Cập Nhật</h2>
			</div>						
			<ul >	
			<form action="" method="post">
					<li id="li_1" >
		<label class="description" for="element_1">Họ Và Tên </label>
		<div>
			<input id="element_1" name="Ho_Va_Ten" class="element text medium" type="text" maxlength="255" value="<?php echo $data['Ho_Va_Ten']; ?>"/> 
		</div> 
		<span class='error'>
	<?php  echo isset($errorName) ? $errorName : "" ?>
	</span>
	</br>
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Giới Tính
 </label>
		<div>
			<input id="element_2" name="Gioi_tinh" class="element text medium" type="text" maxlength="255" value="<?php echo $data['Gioi_tinh']; ?>"/> 
		</div> 
		<span class='error'>
	<?php  echo isset($errorGender) ? $errorGender : "" ?>
	</span>
	</br>
        </li>		<li id="li_6" >
		<label class="description" for="element_6">Năm Sinh
 </label>
		<div>
			<input id="element_6" name="Nam_Sinh" class="element text medium" type="text" maxlength="255" value="<?php echo $data['Nam_Sinh']; ?>"/> 
		</div> 
		<span class='error'>
	<?php  echo isset($errorDate) ? $errorDate : "" ?>
	</span>
	</br>
        </li>		<li id="li_5" >
		<label class="description" for="element_5">Địa CHỉ</label>
		<div>
			<input id="element_5" name="Que_Quan" class="element text medium" type="text" maxlength="255" value="<?php echo $data['Que_Quan']; ?>"/> 
		</div> 
		<span class='error'>
	<?php  echo isset($errorAddress) ? $errorAddress : "" ?>
	</span>
	</br>
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Email </label>
		<div>
			<input id="element_3" name="email" class="element text medium" type="text" maxlength="255" value="<?php echo $data['email']; ?>"/> 
		</div> 
		<span class='error'>
	<?php  echo isset($errorEmail) ? $errorEmail : "" ?>
	</span>
	</br>
		</li>
			</li>		<li id="li_4" >
		<label class="description" for="element_4">SĐT</label>
		<div>
			<input id="element_4" name="SDT" class="element text medium" type="text" maxlength="255" value="<?php echo $data['SDT']; ?>"/> 
		</div>
		<span class='error'>
	<?php  echo isset($errorPhone) ? $errorPhone : "" ?>
	</span>
		</li>
					<li class="buttons">		    
				<input type="submit" name="ok" value="Cập Nhật">
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="http://phongkham2.freevnn.com/website/style/bottom.png" alt="">
	</body>
</html>	